# Generated by Django 2.0 on 2019-06-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_duanzi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duanzi',
            options={'verbose_name': '段子信息', 'verbose_name_plural': '段子信息'},
        ),
    ]
